#pragma once
#include "svr_common.h"
#include "svr_api.h"
#include "svr_defs.h"
#include "svr_standalone_common.h"
#include "svr_log.h"
#include "svr_array.h"
#include "svr_ini.h"
#include "svr_alloc.h"
#include "game_console.h"
#include <Windows.h>
#include <Psapi.h>
#include <strsafe.h>
#include <assert.h>
#include <Psapi.h>
#include "svr_prof.h"
#include <Shlwapi.h>
#include <d3d9.h>
#include <ShlObj_core.h>
#include <MinHook.h>

#include "game_common.h"
#include "game_asm.h"
