#pragma once
#include "svr_common.h"
#include "svr_api.h"
#include "svr_defs.h"
#include "svr_steam_common.h"
#include "svr_standalone_common.h"
#include "svr_log.h"
#include "game_console.h"
#include <Windows.h>
#include <MinHook.h>
#include <Psapi.h>
#include <strsafe.h>
#include <assert.h>
#include <Psapi.h>
#include "svr_prof.h"
#include <Shlwapi.h>
#include <d3d9.h>
