#pragma once
#include "svr_common.h"
#include "svr_defs.h"
#include "svr_log.h"
#include "svr_console.h"
#include "svr_queue.h"
#include "encoder_shared.h"
#include <d3d11.h>
#include <d3d11shadertracing.h>
#include <dxgi1_2.h>
#include <strsafe.h>
#include <dwrite.h>
#include <d2d1_1.h>
#include <malloc.h>
#include <assert.h>
#include <intrin.h>
#include "svr_prof.h"
#include <stb_sprintf.h>
#include "svr_api.h"
#include "svr_ini.h"
#include "svr_alloc.h"
#include <Shlwapi.h>
#include <math.h>
#include <float.h>
#include <TlHelp32.h>
#include <d3d9.h>
#include <Psapi.h>

#include "proc_state.h"
#include "proc_profile_opts.h"
