#pragma once
#include "svr_common.h"
#include "svr_defs.h"
#include "svr_standalone_common.h"
#include <Windows.h>
#include <stdio.h>
#include <strsafe.h>
#include "svr_log.h"
#include "svr_vdf.h"
#include "svr_ini.h"
#include "svr_array.h"
#include <VersionHelpers.h>
#include <stb_sprintf.h>
#include <d3d11.h>
#include <Psapi.h>
#include <WbemIdl.h>
#include "svr_alloc.h"
#include <Shlwapi.h>

#include "launcher_state.h"
